#!/usr/bin/env python
# -*- coding: utf-8 -*-

import torch
import torch.nn as nn
import torch.nn.functional as tnf
from torchvision.models import resnet34
import os


class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super(SpatialAttention, self).__init__()
        assert kernel_size in (3, 7), 'kernel size must be 3 or 7'
        padding = 3 if kernel_size == 7 else 1
        self.conv1 = nn.Conv2d(2, 1, kernel_size, padding=padding, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x = torch.cat([avg_out, max_out], dim=1)
        x = self.conv1(x)
        return self.sigmoid(x)

class DecoderBlock(nn.Module):
    def __init__(self, in_channels, mid_channels, out_channels, upsample_mode='transpose', BN_enable=True):
        super().__init__()
        self.in_channels = in_channels
        self.mid_channels = mid_channels
        self.out_channels = out_channels
        self.upsample_mode = upsample_mode
        self.BN_enable = BN_enable
        self.conv1 = nn.Conv2d(in_channels=in_channels, out_channels=mid_channels, kernel_size=3, stride=1, padding=1, bias=False)
        if self.BN_enable:
            self.norm1 = nn.BatchNorm2d(mid_channels)
        if upsample_mode == 'transpose':
            self.upsample = nn.ConvTranspose2d(
                in_channels=mid_channels, out_channels=out_channels, kernel_size=4, stride=2, padding=1, bias=False
            )
        else:
            self.upsample = nn.PixelShuffle(upscale_factor=2)
            if mid_channels != out_channels * 4:
                self.conv_adjust = nn.Conv2d(mid_channels, out_channels * 4, kernel_size=1, bias=False)
        if self.BN_enable:
            self.norm2 = nn.BatchNorm2d(out_channels)
        self.spatial_attention = SpatialAttention()

    def forward(self, x):
        x = self.conv1(x)
        if self.BN_enable:
            x = self.norm1(x)
        x = tnf.relu(x)
        if self.upsample_mode == 'transpose':
            x = self.upsample(x)
        else:
            if hasattr(self, 'conv_adjust'):
                x = self.conv_adjust(x)
            x = self.upsample(x)
        if self.BN_enable:
            x = self.norm2(x)
        x = tnf.relu(x)
        attention = self.spatial_attention(x)
        x = x * attention
        return x

class Res34_Unet_NoTerrain(nn.Module):
    def __init__(self, inputchannel, outputchannel, BN_enable=True, resnet_pretrain=True, output_size=(161, 161)):
        super().__init__()
        self.BN_enable = BN_enable
        self.resnet = resnet34(pretrained=resnet_pretrain)
        filters = [64, 64, 128, 256, 512] 
        self.output_size = output_size
    
        self.firstconv = nn.Conv2d(in_channels=inputchannel, out_channels=64, kernel_size=7, stride=1, padding=3, bias=False)
        self.firstbn = self.resnet.bn1
        self.firstrelu = tnf.relu
        self.firstmaxpool = nn.MaxPool2d(kernel_size=3, stride=1, padding=1)
        self.encoder1 = self.resnet.layer1
        self.encoder2 = self.resnet.layer2
        self.encoder3 = self.resnet.layer3
        self.encoder4 = self.resnet.layer4
       
        self.center = DecoderBlock(in_channels=filters[4], mid_channels=filters[4] * 4, out_channels=filters[4],
                                   upsample_mode='transpose', BN_enable=self.BN_enable)
        self.decoder0 = DecoderBlock(in_channels=filters[4] + filters[3], mid_channels=filters[3] * 4,
                                     out_channels=filters[3], upsample_mode='transpose', BN_enable=self.BN_enable)
        self.decoder1 = DecoderBlock(in_channels=filters[3] + filters[2], mid_channels=filters[2] * 4,
                                     out_channels=filters[2], upsample_mode='transpose', BN_enable=self.BN_enable)
        self.decoder2 = DecoderBlock(in_channels=filters[2] + filters[1], mid_channels=filters[1] * 4,
                                     out_channels=filters[1], upsample_mode='transpose', BN_enable=self.BN_enable)
        self.dropout = nn.Dropout(p=0.3)
       
        self.final_upsample = nn.Sequential(
            nn.Conv2d(in_channels=filters[1], out_channels=128, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(128) if BN_enable else nn.Identity(),
            nn.ReLU(),
            nn.ConvTranspose2d(in_channels=128, out_channels=64, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(64) if BN_enable else nn.Identity(),
            nn.ReLU(),
            nn.ConvTranspose2d(in_channels=64, out_channels=32, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(32) if BN_enable else nn.Identity(),
            nn.ReLU(),
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(32) if BN_enable else nn.Identity(),
            nn.ReLU(),
            nn.Conv2d(in_channels=32, out_channels=outputchannel, kernel_size=3, padding=1, bias=False),
            nn.AdaptiveAvgPool2d(output_size)
        )
        if resnet_pretrain:
            state_dict = self.resnet.state_dict()
            if inputchannel != 3:
                pretrained_conv1_weight = state_dict['conv1.weight']
                new_conv1_weight = torch.zeros(64, inputchannel, 7, 7, device=pretrained_conv1_weight.device)
                for i in range(inputchannel):
                    if i < 3:
                        new_conv1_weight[:, i, :, :] = pretrained_conv1_weight[:, i, :, :]
                    else:
                        new_conv1_weight[:, i, :, :] = pretrained_conv1_weight[:, :3, :, :].mean(dim=1)
                state_dict['conv1.weight'] = new_conv1_weight
            self.firstconv.weight.data = state_dict['conv1.weight']
            print("ResNet34 pretrained weights loaded, adapted for input channels:", inputchannel)

    def forward(self, x):
     
        x = self.firstconv(x)  
        x = self.firstbn(x)
        x = self.firstrelu(x)
        x_ = self.firstmaxpool(x)  
        e1 = self.encoder1(x_) 
        e2 = self.encoder2(e1)  
        e3 = self.encoder3(e2) 
        e4 = self.encoder4(e3) 
        center = self.center(e4)  
        center = tnf.interpolate(center, size=(e3.size(2), e3.size(3)), mode='bilinear', align_corners=False) 
        d1 = self.decoder0(torch.cat([center, e3], dim=1)) 
        d1 = tnf.interpolate(d1, size=(e2.size(2), e2.size(3)), mode='bilinear', align_corners=False) 
        d2 = self.decoder1(torch.cat([d1, e2], dim=1))  
        d2 = tnf.interpolate(d2, size=(e1.size(2), e1.size(3)), mode='bilinear', align_corners=False) 
        d3 = self.decoder2(torch.cat([d2, e1], dim=1)) 
        d3 = self.dropout(d3)
        output = self.final_upsample(d3) 
        return output

class ModifiedRes34_Unet_NoTerrain(Res34_Unet_NoTerrain):
    def __init__(self, inputchannel, outputchannel, BN_enable=True, resnet_pretrain=True, output_size=(161, 161)):
        super().__init__(inputchannel, outputchannel, BN_enable=BN_enable, resnet_pretrain=resnet_pretrain, output_size=output_size)

    c = Model(a)
    print(f"Output shape: {c.shape}")  # 应输出 torch.Size([5, 1, 161, 161])
